// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACn96j7YU7Py-wgFe0G42KaFBxr7FPvNI',
    appId: '1:55066623021:web:9c0fb961c43e5ae76e4ca4',
    messagingSenderId: '55066623021',
    projectId: 'kigali-city-directory-18eed',
    authDomain: 'kigali-city-directory-18eed.firebaseapp.com',
    storageBucket: 'kigali-city-directory-18eed.firebasestorage.app',
    measurementId: 'G-MSVBDLGVVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DEkKiVyrl1majIih70laKumpI_GNGsI',
    appId: '1:55066623021:android:9499b5f68dce6e176e4ca4',
    messagingSenderId: '55066623021',
    projectId: 'kigali-city-directory-18eed',
    storageBucket: 'kigali-city-directory-18eed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpiN6EIbd3mpSHisjKE64nSEIPNkoV58',
    appId: '1:55066623021:ios:f249de0527dc7f176e4ca4',
    messagingSenderId: '55066623021',
    projectId: 'kigali-city-directory-18eed',
    storageBucket: 'kigali-city-directory-18eed.firebasestorage.app',
    iosBundleId: 'com.example.iriza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpiN6EIbd3mpSHisjKE64nSEIPNkoV58',
    appId: '1:55066623021:ios:f249de0527dc7f176e4ca4',
    messagingSenderId: '55066623021',
    projectId: 'kigali-city-directory-18eed',
    storageBucket: 'kigali-city-directory-18eed.firebasestorage.app',
    iosBundleId: 'com.example.iriza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACn96j7YU7Py-wgFe0G42KaFBxr7FPvNI',
    appId: '1:55066623021:web:a789a3334f76fb716e4ca4',
    messagingSenderId: '55066623021',
    projectId: 'kigali-city-directory-18eed',
    authDomain: 'kigali-city-directory-18eed.firebaseapp.com',
    storageBucket: 'kigali-city-directory-18eed.firebasestorage.app',
    measurementId: 'G-7F5MF8PWD6',
  );
}
